# Generated by Django 4.2.4 on 2023-08-18 16:17

import apps.well_passport.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("organizations", "0002_alter_organization_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("well_section", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WellPassport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("project_name", models.CharField(blank=True, max_length=100)),
                ("well_number", models.CharField(blank=True, max_length=100)),
                ("passport_type", models.CharField(blank=True, max_length=100)),
                ("republic", models.CharField(max_length=100)),
                ("region", models.CharField(max_length=100)),
                ("district", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=200)),
                ("well_owner", models.CharField(max_length=200)),
                ("mailing_adress", models.CharField(max_length=200)),
                ("NL", models.CharField(max_length=40)),
                ("SL", models.CharField(max_length=40)),
                ("ground_lvl", models.FloatField()),
                ("well_type", models.CharField(max_length=200)),
                ("well_purpose", models.CharField(max_length=200)),
                ("drilling_method", models.CharField(max_length=200)),
                ("rig", models.CharField(max_length=200)),
                ("project_owner", models.CharField(max_length=200)),
                ("drilling_company", models.CharField(max_length=200)),
                ("start", models.DateField()),
                ("end", models.DateField()),
                ("finishing", models.DateField()),
                ("pump_power", models.FloatField()),
                ("pump_column", models.FloatField()),
                ("debit", models.FloatField()),
                ("gis_data", models.CharField(max_length=400)),
                ("ofr_data", models.CharField(max_length=400)),
                ("cementation_data", models.CharField(max_length=400)),
                (
                    "gis",
                    models.FileField(
                        upload_to="well_passport/gis/",
                        validators=[apps.well_passport.models.validate_file_size],
                    ),
                ),
                (
                    "analyses",
                    models.FileField(
                        upload_to="well_passport/analyses/",
                        validators=[apps.well_passport.models.validate_file_size],
                    ),
                ),
                (
                    "acts",
                    models.FileField(
                        upload_to="well_passport/acts/",
                        validators=[apps.well_passport.models.validate_file_size],
                    ),
                ),
                (
                    "sro",
                    models.FileField(
                        upload_to="well_passport/sro/",
                        validators=[apps.well_passport.models.validate_file_size],
                    ),
                ),
                ("others_apps_name", models.CharField(max_length=200)),
                (
                    "others_apps",
                    models.FileField(
                        upload_to="well_passport/others/",
                        validators=[apps.well_passport.models.validate_file_size],
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="well_passport",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "well_section",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passport",
                        to="well_section.wellsection",
                    ),
                ),
            ],
        ),
    ]
