# Generated by Django 4.2.4 on 2023-08-20 17:37

import apps.well_passport.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("well_section", "0001_initial"),
        ("well_passport", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wellpassport",
            name="NL",
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="wellpassport",
            name="SL",
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="wellpassport",
            name="acts",
            field=models.FileField(
                null=True,
                upload_to="well_passport/acts/",
                validators=[apps.well_passport.models.validate_file_size],
            ),
        ),
        migrations.AlterField(
            model_name="wellpassport",
            name="analyses",
            field=models.FileField(
                null=True,
                upload_to="well_passport/analyses/",
                validators=[apps.well_passport.models.validate_file_size],
            ),
        ),
        migrations.AlterField(
            model_name="wellpassport",
            name="cementation_data",
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="wellpassport",
            name="debit",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="wellpassport",
            name="district",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="wellpassport",
            name="drilling_company",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="wellpassport",
            name="drilling_method",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="wellpassport",
            name="end",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="wellpassport",
            name="finishing",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="wellpassport",
            name="gis",
            field=models.FileField(
                null=True,
                upload_to="well_passport/gis/",
                validators=[apps.well_passport.models.validate_file_size],
            ),
        ),
        migrations.AlterField(
            model_name="wellpassport",
            name="gis_data",
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="wellpassport",
            name="ground_lvl",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="wellpassport",
            name="location",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="wellpassport",
            name="mailing_adress",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="wellpassport",
            name="ofr_data",
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="wellpassport",
            name="others_apps",
            field=models.FileField(
                null=True,
                upload_to="well_passport/others/",
                validators=[apps.well_passport.models.validate_file_size],
            ),
        ),
        migrations.AlterField(
            model_name="wellpassport",
            name="others_apps_name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="wellpassport",
            name="project_owner",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="wellpassport",
            name="pump_column",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="wellpassport",
            name="pump_power",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="wellpassport",
            name="region",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="wellpassport",
            name="republic",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="wellpassport",
            name="rig",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="wellpassport",
            name="sro",
            field=models.FileField(
                null=True,
                upload_to="well_passport/sro/",
                validators=[apps.well_passport.models.validate_file_size],
            ),
        ),
        migrations.AlterField(
            model_name="wellpassport",
            name="start",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="wellpassport",
            name="well_owner",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="wellpassport",
            name="well_purpose",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="wellpassport",
            name="well_section",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="passport",
                to="well_section.wellsection",
            ),
        ),
        migrations.AlterField(
            model_name="wellpassport",
            name="well_type",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
