# Generated by Django 4.2.4 on 2023-08-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_customuser_confirmation_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="confirmation_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="confirmation_code_dt",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
