# Generated by Django 4.2.4 on 2023-08-22 22:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_customuser_confirmation_code_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="is_active",
            new_name="confirmed",
        ),
    ]
