version: '1'
services:
  # Сервис для приложения Django
  web:
    build:
      context: .
    # image: enhyp-app:latest  # Замените на имя образа вашего приложения
    container_name: enhyp_app
    ports:
      - "80:8000"  # хост:контейнер
    environment:
      - DEBUG=True  # Установите переменные окружения для вашего приложения Django
      - DB_TYPE=postgress
    command: python manage.py makemigrations && python manage.py migrate && python src/manage.py runserver 0.0.0.0:8000
    restart: always
    depends_on:
      - db  # Указываем зависимость от сервиса db (нашей базы данных PostgreSQL)

  # Сервис для базы данных PostgreSQL
  db:
    image: postgres:13  # Используем образ PostgreSQL версии 13 (можете выбрать другую версию)
    container_name: enhyp_db
    environment:
      POSTGRES_DB: enh_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password_123
    ports:
      - "5432:5432"