version: '1'
services:
  # Сервис для приложения Django
  web:
    build:
      context: .
    # image: enhyp-app:latest  # Замените на имя образа вашего приложения
    container_name: enhyp_app
    ports:
      - "80:8000"  # хост:контейнер
    environment:
      - DEBUG=True  # Установите переменные окружения для вашего приложения Django
      - DB_TYPE=postgres
      - SECRET_KEY='django-insecure-(wv(*iq0s#t-c0+cayw!*bdkf#$_9_r9d7=r0icia-1ha5)@j#'
    command: ./docker-entrypoint.sh
    restart: always
    depends_on:
      - db  # Указываем зависимость от сервиса db (нашей базы данных PostgreSQL)

  # Сервис для базы данных PostgreSQL
  db:
    image: postgres:13  # Используем образ PostgreSQL версии 13
    container_name: enhyp_db
    environment:
      # POSTGRES_DB: enh_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password_123
      PGUSER: admin
    ports:
      - "5432:5432"
    volumes:
      - .db_data:/var/lib/postgresql