# Generated by Django 4.2.4 on 2023-08-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_alter_organization_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="ceo_name",
            field=models.CharField(default="test_name", max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organization",
            name="originator_name",
            field=models.CharField(default="t", max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="organization",
            name="originator_position",
            field=models.CharField(default="t", max_length=25),
            preserve_default=False,
        ),
    ]
