# Generated by Django 4.2.4 on 2023-08-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "organizations",
            "0003_organization_ceo_name_organization_originator_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
