# Generated by Django 4.2.4 on 2023-08-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0004_alter_organization_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="confirmation_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="confirmation_code_dt",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
