# Generated by Django 4.2.3 on 2023-07-19 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Zso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("k_f_min", models.FloatField()),
                ("k_f_max", models.FloatField()),
                ("i_min", models.FloatField()),
                ("i_max", models.FloatField()),
                ("alfa_min", models.FloatField()),
                ("alfa_max", models.FloatField()),
                ("m_min", models.FloatField()),
                ("m_max", models.FloatField()),
                ("por_min", models.FloatField()),
                ("por_max", models.FloatField()),
                ("well_numbers", models.IntegerField()),
                ("debits", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zso",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
