# Generated by Django 4.2.3 on 2023-07-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("zso", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="zso",
            name="b_size",
            field=models.FloatField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="zso",
            name="d_t",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="zso",
            name="iteration_count",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="zso",
            name="n_step",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="zso",
            name="n_x",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="zso",
            name="n_x_skv",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="zso",
            name="n_y",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="zso",
            name="n_y_skv",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="zso",
            name="type",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
