# Generated by Django 4.2.4 on 2023-08-09 23:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("zso", "0002_zso_b_size_zso_d_t_zso_iteration_count_zso_n_step_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="zso",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
