# Generated by Django 4.2.4 on 2023-09-22 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0005_organization_confirmation_code_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Crm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=200)),
                ("project_status", models.BooleanField(default=False)),
                (
                    "contract_file",
                    models.FileField(null=True, upload_to="crm/contracts"),
                ),
                ("note", models.CharField(max_length=200, null=True)),
                ("work_list", models.CharField(max_length=200, null=True)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crm",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crm",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Zso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zso_name", models.CharField(max_length=12)),
                ("zso_status", models.BooleanField(default=False)),
                ("zso_file", models.FileField(null=True, upload_to="crm/zso/project")),
                ("eks_file", models.FileField(null=True, upload_to="crm/zso/eks")),
                ("sez_file", models.FileField(null=True, upload_to="crm/zso/sez")),
                ("note", models.CharField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                (
                    "crm",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zso",
                        to="crm.crm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resources",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resources_name", models.CharField(max_length=12)),
                ("resources_status", models.BooleanField(default=False)),
                (
                    "resources_file",
                    models.FileField(null=True, upload_to="crm/resources/project"),
                ),
                (
                    "protocol_file",
                    models.FileField(null=True, upload_to="crm/resources/protocol"),
                ),
                (
                    "plan_file",
                    models.FileField(null=True, upload_to="crm/resources/plan"),
                ),
                ("note", models.CharField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                (
                    "crm",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="crm.crm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pkk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pkk_name", models.CharField(max_length=12)),
                ("pkk_status", models.BooleanField(default=False)),
                ("pkk_file", models.FileField(null=True, upload_to="crm/pkk/project")),
                ("eks_file", models.FileField(null=True, upload_to="crm/pkk/eks")),
                ("sez_file", models.FileField(null=True, upload_to="crm/pkk/sez")),
                ("note", models.CharField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                (
                    "crm",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pkk",
                        to="crm.crm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_name", models.CharField(max_length=12)),
                ("license_status", models.BooleanField(default=False)),
                ("license_file", models.FileField(null=True, upload_to="crm/license")),
                ("note", models.CharField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                (
                    "second_license_file",
                    models.FileField(null=True, upload_to="crm/license"),
                ),
                ("second_note", models.CharField(max_length=200, null=True)),
                ("second_created_at", models.DateTimeField(blank=True, null=True)),
                ("second_end_at", models.DateTimeField(blank=True, null=True)),
                (
                    "crm",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="license",
                        to="crm.crm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Gin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gin_name", models.CharField(max_length=12)),
                ("gin_status", models.BooleanField(default=False)),
                ("gin_file", models.FileField(null=True, upload_to="crm/gin/project")),
                ("eks_file", models.FileField(null=True, upload_to="crm/gin/eks")),
                ("note", models.CharField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                (
                    "crm",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gin",
                        to="crm.crm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Development",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("development_name", models.CharField(max_length=12)),
                ("development_status", models.BooleanField(default=False)),
                (
                    "development_file",
                    models.FileField(null=True, upload_to="crm/development/project"),
                ),
                (
                    "eks_file",
                    models.FileField(null=True, upload_to="crm/development/eks"),
                ),
                ("note", models.CharField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("end_at", models.DateTimeField(blank=True, null=True)),
                (
                    "crm",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="development",
                        to="crm.crm",
                    ),
                ),
            ],
        ),
    ]
